blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/your-username/VisionDesk/wiki
    about: Check our documentation for common questions and guides
  - name: 💬 Discussions
    url: https://github.com/your-username/VisionDesk/discussions
    about: Join our community discussions for general questions and ideas
  - name: 🔒 Security Issues
    url: mailto:security@your-domain.com
    about: Please report security vulnerabilities privately via email
